var tipos = [
    {
    pkmnType:"normal",
    trad:"NORMAL", 
    color:"#a8a878"
    },
    {
    pkmnType:"fire",
    trad:"FUEGO", 
    color:"#f08030"
    },
    {
    pkmnType:"water",
    trad:"AGUA", 
    color:"#6890f0"
    },
    {
    pkmnType:"grass",
    trad:"PLANTA", 
    color:"#78c850"
    },
    {
    pkmnType:"electric",
    trad:"ELECTRICO", 
    color:"#f8d030"
    },
    {
    pkmnType:"ice",
    trad:"HIELO", 
    color:"#98d8d8"
    },
    {
    pkmnType:"fighting",
    trad:"LUCHA", 
    color:"#c03028"
    },
    {
    pkmnType:"poison",
    trad:"VENENO", 
    color:"#a040a0"
    },
    {
    pkmnType:"ground",
    trad:"TIERRA", 
    color:"#e0c068"
    },
    {
    pkmnType:"flying",
    trad:"VOLADOR", 
    color:"#a890f0"
    },
    {
    pkmnType:"psychic",
    trad:"PSIQUICO", 
    color:"#f85888"
    },
    {
    pkmnType:"bug",
    trad:"BICHO", 
    color:"#a8b820"
    },
    {
    pkmnType:"rock",
    trad:"ROCA", 
    color:"#b8a038"
    },
    {
    pkmnType:"ghost",
    trad:"FANTASMA", 
    color:"#705898"
    },
    {
    pkmnType:"dark",
    trad:"SINIESTRO", 
    color:"#705848"
    },
    {
    pkmnType:"dragon",
    trad:"DRAGON", 
    color:"#7038f8"
    },
    {
    pkmnType:"steel",
    trad:"ACERO", 
    color:"#b8b8d0"
    },
    {
    pkmnType:"fairy",
    trad:"HADA", 
    color:"#f0b6bc"
    },
]

